name: inventory_control
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  flutter_staggered_grid_view: ^0.6.2
  get: 4.6.5
  google_fonts: ^4.0.3
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true
