name: inventory_control
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  auto_size_text: ^3.0.0
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dropdown_search: ^5.0.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_colorpicker: ^1.0.3
  flutter_iconpicker:
    path: packages/FlutterIconPicker
  flutter_localizations:
    sdk: flutter
  flutter_speed_dial: ^6.2.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  font_awesome_flutter: ^10.4.0
  get: 4.6.5
  google_fonts: ^4.0.3
  group_button: ^5.2.2
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  lottie: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/dialog/
